# Compiler and flags
CXX = g++
# -pthread is required: the engine runs its search on std::thread.
# -MMD -MP emit .d dependency files so editing a header rebuilds dependents.
CXXFLAGS = -std=c++17 -O2 -Wall -pthread -MMD -MP -I./src

# SFML libraries to link against
SFML_LIBS = -lsfml-graphics -lsfml-window -lsfml-system
LDFLAGS = -pthread

# Source files (automatically find all .cpp files in src/, src/engine/, and src/gui/)
SRC = $(wildcard src/*.cpp src/engine/*.cpp src/gui/*.cpp)

# Object and dependency files generated from source files
OBJ = $(SRC:.cpp=.o)
DEP = $(OBJ:.o=.d)

# Name of the final executable
EXEC = chessbot

# Default target: build the executable
all: $(EXEC)

# Link object files to create the executable
$(EXEC): $(OBJ)
	$(CXX) $(OBJ) -o $@ $(SFML_LIBS) $(LDFLAGS)

# Compile .cpp files to .o object files
%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Header dependency tracking (generated by -MMD)
-include $(DEP)

# --- Tests ---
# The engine sources only (no GUI, no main), so test binaries link without SFML.
ENGINE_SRC = $(wildcard src/engine/*.cpp)
# game_manager has no GUI dependency, so game-state tests link without SFML too.
GM_SRC = src/game_manager.cpp
# The GUI sources, for the input test. It links SFML for the types the GUI is
# written in, but never opens a window.
GUI_SRC = $(wildcard src/gui/*.cpp)
TESTS = tests/perft tests/match tests/gamestate tests/evalref tests/bench tests/timecontrol tests/see_test tests/bitboard_test tests/guiinput tests/pgn

# Test binaries LINK these objects rather than recompiling the sources.
#
# They used to name $(ENGINE_SRC) as prerequisites and hand every .cpp to one
# g++ call. That silently broke header dependency tracking: -MMD writes its .d
# per translation unit, and with a single -o every source overwrote the last,
# so tests/bench.d ended up describing whichever file happened to compile last
# and listed none of the headers. Editing a header then printed "Nothing to be
# done for 'tests'" and left ten stale binaries testing the previous engine —
# a green suite proving nothing. One object per source restores a correct .d
# for each, and stops rebuilding 21 engine sources ten times over.
ENGINE_OBJ = $(ENGINE_SRC:.cpp=.o)
GM_OBJ = $(GM_SRC:.cpp=.o)
GUI_OBJ = $(GUI_SRC:.cpp=.o)

TEST_SRC = $(wildcard tests/*.cpp)
TEST_OBJ = $(TEST_SRC:.cpp=.o)
TEST_DEP = $(TEST_OBJ:.o=.d)
-include $(TEST_DEP)

# perft guards move generation: leaf counts must match published references.
tests/perft: tests/perft.o $(ENGINE_OBJ)
	$(CXX) $^ -o $@ $(LDFLAGS)

# match plays two search configurations against each other to measure strength.
tests/match: tests/match.o $(ENGINE_OBJ)
	$(CXX) $^ -o $@ $(LDFLAGS)

# gamestate guards that a finished game actually stops accepting moves.
tests/gamestate: tests/gamestate.o $(ENGINE_OBJ) $(GM_OBJ)
	$(CXX) $^ -o $@ $(LDFLAGS)

# evalref guards every evaluation term against unintended change.
tests/evalref: tests/evalref.o $(ENGINE_OBJ)
	$(CXX) $^ -o $@ $(LDFLAGS)

# bench produces the search's node-count signature.
tests/bench: tests/bench.o $(ENGINE_OBJ)
	$(CXX) $^ -o $@ $(LDFLAGS)

# timecontrol guards that a search with a budget returns inside it.
tests/timecontrol: tests/timecontrol.o $(ENGINE_OBJ)
	$(CXX) $^ -o $@ $(LDFLAGS)

# see_test checks static exchange evaluation against hand-computed positions.
tests/see_test: tests/see_test.o $(ENGINE_OBJ)
	$(CXX) $^ -o $@ $(LDFLAGS)

# bitboard_test validates the magic tables exhaustively and cross-checks the
# attack, checker and pin queries against the mailbox engine.
tests/bitboard_test: tests/bitboard_test.o $(ENGINE_OBJ)
	$(CXX) $^ -o $@ $(LDFLAGS)

# guiinput drives the board input state machine headlessly: click-to-move,
# drag-and-drop, and the promotion dialog's hitboxes. The dialog's hitboxes and
# its drawing were computed separately once, and drifted apart the moment the
# side panel widened the window; this pins them to the same geometry.
tests/guiinput: tests/guiinput.o $(ENGINE_OBJ) $(GM_OBJ) $(GUI_OBJ)
	$(CXX) $^ -o $@ $(SFML_LIBS) $(LDFLAGS)

# pgn guards the SAN export. Notation is unambiguous only if the writer does
# the disambiguation work, and a viewer handed "Nf3" where it needed "Nbd2"
# replays a different game than the one that was played.
tests/pgn: tests/pgn.o $(ENGINE_OBJ)
	$(CXX) $^ -o $@ $(LDFLAGS)

tests: $(TESTS)

# Run the movegen regression test.
test-perft: tests/perft
	./tests/perft

# Run a short match. Override the defaults, e.g.
#   make test-match MATCH_ARGS="100 4 12345"
MATCH_ARGS ?= 25 4
test-match: tests/match
	./tests/match $(MATCH_ARGS)

# Run the game-over regression test.
test-gamestate: tests/gamestate
	./tests/gamestate

# Compare every evaluation term against the stored reference.
test-evalref: tests/evalref
	./tests/evalref

# Rewrite the evaluation reference. Only after reviewing the reported term
# changes and deciding they are intended.
evalref-regen: tests/evalref
	./tests/evalref --regen

# Print the search node-count signature at any depth.
#   make bench BENCH_DEPTH=8
BENCH_DEPTH ?=
bench: tests/bench
	./tests/bench $(BENCH_DEPTH)

# Compare the search against the stored signature. Fails if the tree changed.
test-bench: tests/bench
	./tests/bench --check

# Rewrite the stored signature, once the new numbers have been reviewed.
bench-regen: tests/bench
	./tests/bench --regen

# Check that a time-limited search respects its budget.
test-timecontrol: tests/timecontrol
	./tests/timecontrol

# Check static exchange evaluation against hand-computed positions.
test-see: tests/see_test
	./tests/see_test

# Validate the magic tables and the bitboard attack queries.
test-bitboard: tests/bitboard_test
	./tests/bitboard_test

# Check the board input: selecting, click-to-move, dragging, promotion clicks.
test-guiinput: tests/guiinput
	./tests/guiinput

# Check PGN export: SAN, disambiguation, numbering, whole documents.
test-pgn: tests/pgn
	./tests/pgn

# Check the UCI protocol. Needs the main binary, since UCI is a mode of it.
# A protocol bug is invisible to every other test here: the engine plays fine
# through its own GUI while being undrivable by any external tool.
test-uci: $(EXEC)
	python3 tests/uci_smoke.py

# --- Profiling ---
#
# gprof rather than perf: perf is unavailable under WSL, which is why gmon.out
# has been in .gitignore since the 2026-08-10 session.
#
#   make profile                 profile tests/bench at depth 6
#   make profile PROF_DEPTH=7    deeper, if the shape is depth-dependent
#
# Compiled on its own and deliberately *without* -MMD -MP. This is one g++ call
# with many sources and a single -o, which is exactly the shape that rewrites
# the .d once per translation unit and leaves it describing only whichever file
# compiled last. That is what left ten stale test binaries passing in silence
# (see the tests/ rules above); it must not be reintroduced here.
#
# -O2 is kept so the profile describes the binary that actually runs. Inlining
# therefore charges a callee's time to its caller within a translation unit —
# fine at the granularity this is used for, since evaluate(), generateLegalMoves()
# and makeMove() live in different ones and are not inlined across them.
PROF_FLAGS = -std=c++17 -O2 -pg -Wall -pthread -I./src
PROF_BIN   = tests/bench-prof
PROF_DEPTH ?= 6

$(PROF_BIN): tests/bench.cpp $(ENGINE_SRC)
	$(CXX) $(PROF_FLAGS) $^ -o $@ $(LDFLAGS) -pg

profile: $(PROF_BIN)
	@rm -f gmon.out
	./$(PROF_BIN) $(PROF_DEPTH) > /dev/null
	@echo "--- flat profile, depth $(PROF_DEPTH) ---"
	@gprof -b -p $(PROF_BIN) gmon.out | head -22

# Play on Lichess. Needs LICHESS_BOT_TOKEN in the environment and a lichess-bot
# checkout (external, AGPL-3.0) — see lichess/README.md.
lichess:
	./lichess/run.sh

# Clean up build files
clean:
	rm -f $(OBJ) $(DEP) $(TEST_OBJ) $(TEST_DEP) $(EXEC) $(TESTS) $(PROF_BIN) gmon.out

# Clean and rebuild the project
remake:
	$(MAKE) clean
	$(MAKE) all

# Mark these targets as not actual files
.PHONY: all clean remake lichess profile tests test-perft test-match test-gamestate test-evalref evalref-regen bench test-bench bench-regen test-timecontrol test-see test-bitboard test-guiinput test-pgn test-uci
