# Compiler and flags
CXX = g++
# -pthread is required: the engine runs its search on std::thread.
# -MMD -MP emit .d dependency files so editing a header rebuilds dependents.
CXXFLAGS = -std=c++17 -O2 -Wall -pthread -MMD -MP -I./src

# SFML libraries to link against
SFML_LIBS = -lsfml-graphics -lsfml-window -lsfml-system
LDFLAGS = -pthread

# Source files (automatically find all .cpp files in src/, src/engine/, and src/gui/)
SRC = $(wildcard src/*.cpp src/engine/*.cpp src/gui/*.cpp)

# Object and dependency files generated from source files
OBJ = $(SRC:.cpp=.o)
DEP = $(OBJ:.o=.d)

# Name of the final executable
EXEC = chessbot

# Default target: build the executable
all: $(EXEC)

# Link object files to create the executable
$(EXEC): $(OBJ)
	$(CXX) $(OBJ) -o $@ $(SFML_LIBS) $(LDFLAGS)

# Compile .cpp files to .o object files
%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Header dependency tracking (generated by -MMD)
-include $(DEP)

# --- Tests ---
# The engine sources only (no GUI, no main), so test binaries link without SFML.
ENGINE_SRC = $(wildcard src/engine/*.cpp)
# game_manager has no GUI dependency, so game-state tests link without SFML too.
GM_SRC = src/game_manager.cpp
TESTS = tests/perft tests/match tests/gamestate tests/evalref

# perft guards move generation: leaf counts must match published references.
tests/perft: tests/perft.cpp $(ENGINE_SRC)
	$(CXX) $(CXXFLAGS) $^ -o $@ $(LDFLAGS)

# match plays two search configurations against each other to measure strength.
tests/match: tests/match.cpp $(ENGINE_SRC)
	$(CXX) $(CXXFLAGS) $^ -o $@ $(LDFLAGS)

# gamestate guards that a finished game actually stops accepting moves.
tests/gamestate: tests/gamestate.cpp $(ENGINE_SRC) $(GM_SRC)
	$(CXX) $(CXXFLAGS) $^ -o $@ $(LDFLAGS)

# evalref guards every evaluation term against unintended change.
tests/evalref: tests/evalref.cpp $(ENGINE_SRC)
	$(CXX) $(CXXFLAGS) $^ -o $@ $(LDFLAGS)

tests: $(TESTS)

# Run the movegen regression test.
test-perft: tests/perft
	./tests/perft

# Run a short match. Override the defaults, e.g.
#   make test-match MATCH_ARGS="100 4 12345"
MATCH_ARGS ?= 25 4
test-match: tests/match
	./tests/match $(MATCH_ARGS)

# Run the game-over regression test.
test-gamestate: tests/gamestate
	./tests/gamestate

# Compare every evaluation term against the stored reference.
test-evalref: tests/evalref
	./tests/evalref

# Rewrite the evaluation reference. Only after reviewing the reported term
# changes and deciding they are intended.
evalref-regen: tests/evalref
	./tests/evalref --regen

# Clean up build files
clean:
	rm -f $(OBJ) $(DEP) $(EXEC) $(TESTS)

# Clean and rebuild the project
remake:
	$(MAKE) clean
	$(MAKE) all

# Mark these targets as not actual files
.PHONY: all clean remake tests test-perft test-match test-gamestate test-evalref evalref-regen
